// Curated Polish locative forms for every city that gets a /miasto page.
// The generic polishLocative() from @nomideusz/svelte-search mangles the
// long tail (Bolesławiec → "Bolesławiecie", Dębica → "Dębicie"), so — like
// yoga's nameLoc DB column — the forms are data, not an algorithm. Cities
// missing from the table (future dataset growth) fall back to the always
// correct "w miejscowości {Name}" phrasing rather than a guessed form.

const CITY_LOCATIVE: Record<string, string> = {
	'Aleksandrów Kujawski': 'Aleksandrowie Kujawskim',
	'Aleksandrów Łódzki': 'Aleksandrowie Łódzkim',
	Andrychów: 'Andrychowie',
	Augustów: 'Augustowie',
	Barczewo: 'Barczewie',
	Barlinek: 'Barlinku',
	Bartoszyce: 'Bartoszycach',
	Będzin: 'Będzinie',
	Bełchatów: 'Bełchatowie',
	'Biała Podlaska': 'Białej Podlaskiej',
	Białobrzegi: 'Białobrzegach',
	Białogard: 'Białogardzie',
	Białystok: 'Białymstoku',
	'Bielany Wrocławskie': 'Bielanach Wrocławskich',
	Bielawa: 'Bielawie',
	'Bielsk Podlaski': 'Bielsku Podlaskim',
	'Bielsko-Biała': 'Bielsku-Białej',
	Bieruń: 'Bieruniu',
	Biłgoraj: 'Biłgoraju',
	Biskupiec: 'Biskupcu',
	Błonie: 'Błoniu',
	Bogatynia: 'Bogatyni',
	'Boguszów-Gorce': 'Boguszowie-Gorcach',
	Bolesławiec: 'Bolesławcu',
	Bolszewo: 'Bolszewie',
	Borkowo: 'Borkowie',
	Braniewo: 'Braniewie',
	Brodnica: 'Brodnicy',
	Brwinów: 'Brwinowie',
	Brzeg: 'Brzegu',
	'Brzeg Dolny': 'Brzegu Dolnym',
	Brzesko: 'Brzesku',
	Brzeziny: 'Brzezinach',
	Brzozów: 'Brzozowie',
	Buk: 'Buku',
	'Busko-Zdrój': 'Busku-Zdroju',
	Bydgoszcz: 'Bydgoszczy',
	'Bystrzyca Kłodzka': 'Bystrzycy Kłodzkiej',
	Bytom: 'Bytomiu',
	Bytów: 'Bytowie',
	Chełm: 'Chełmie',
	Chełmno: 'Chełmnie',
	Chodzież: 'Chodzieży',
	Chojnice: 'Chojnicach',
	Chojnów: 'Chojnowie',
	Chorzów: 'Chorzowie',
	Choszczno: 'Choszcznie',
	Chrzanów: 'Chrzanowie',
	Ciechanów: 'Ciechanowie',
	Ciechocinek: 'Ciechocinku',
	Cieszyn: 'Cieszynie',
	Czaplinek: 'Czaplinku',
	Czarnków: 'Czarnkowie',
	'Czechowice-Dziedzice': 'Czechowicach-Dziedzicach',
	Czeladź: 'Czeladzi',
	Czersk: 'Czersku',
	'Czerwionka-Leszczyny': 'Czerwionce-Leszczynach',
	Częstochowa: 'Częstochowie',
	Człuchów: 'Człuchowie',
	'Dąbrowa Górnicza': 'Dąbrowie Górniczej',
	Dąbrówka: 'Dąbrówce',
	Darłowo: 'Darłowie',
	Dębica: 'Dębicy',
	Dęblin: 'Dęblinie',
	'Dębnica Kaszubska': 'Dębnicy Kaszubskiej',
	Dębno: 'Dębnie',
	Dobra: 'Dobrej',
	'Dobre Miasto': 'Dobrym Mieście',
	'Drawsko Pomorskie': 'Drawsku Pomorskim',
	Drezdenko: 'Drezdenku',
	Działdowo: 'Działdowie',
	Działoszyn: 'Działoszynie',
	Dzierżoniów: 'Dzierżoniowie',
	Elbląg: 'Elblągu',
	Ełk: 'Ełku',
	Garwolin: 'Garwolinie',
	Gdańsk: 'Gdańsku',
	Gdynia: 'Gdyni',
	Giżycko: 'Giżycku',
	Gliwice: 'Gliwicach',
	Głogów: 'Głogowie',
	'Głogów Małopolski': 'Głogowie Małopolskim',
	Głowno: 'Głownie',
	Głubczyce: 'Głubczycach',
	Głuchołazy: 'Głuchołazach',
	Gniezno: 'Gnieźnie',
	Gołdap: 'Gołdapi',
	Goleniów: 'Goleniowie',
	'Golub-Dobrzyń': 'Golubiu-Dobrzyniu',
	Góra: 'Górze',
	'Góra Kalwaria': 'Górze Kalwarii',
	Gorlice: 'Gorlicach',
	'Gorzów Wielkopolski': 'Gorzowie Wielkopolskim',
	Gostyń: 'Gostyniu',
	Gostynin: 'Gostyninie',
	Grajewo: 'Grajewie',
	Grodków: 'Grodkowie',
	'Grodzisk Mazowiecki': 'Grodzisku Mazowieckim',
	'Grodzisk Wielkopolski': 'Grodzisku Wielkopolskim',
	Grójec: 'Grójcu',
	Grudziądz: 'Grudziądzu',
	Gryfice: 'Gryficach',
	Gryfino: 'Gryfinie',
	Gubin: 'Gubinie',
	Hrubieszów: 'Hrubieszowie',
	Iława: 'Iławie',
	Inowrocław: 'Inowrocławiu',
	Jabłonna: 'Jabłonnie',
	Janki: 'Jankach',
	'Janów Lubelski': 'Janowie Lubelskim',
	Jarocin: 'Jarocinie',
	Jarosław: 'Jarosławiu',
	Jasin: 'Jasinie',
	Jasło: 'Jaśle',
	'Jastrzębie-Zdrój': 'Jastrzębiu-Zdroju',
	Jawor: 'Jaworze',
	Jaworzno: 'Jaworznie',
	Jędrzejów: 'Jędrzejowie',
	'Jelcz-Laskowice': 'Jelczu-Laskowicach',
	'Jelenia Góra': 'Jeleniej Górze',
	Józefosław: 'Józefosławiu',
	Józefów: 'Józefowie',
	Kalisz: 'Kaliszu',
	'Kamień Pomorski': 'Kamieniu Pomorskim',
	'Kamienna Góra': 'Kamiennej Górze',
	Karpacz: 'Karpaczu',
	Kartuzy: 'Kartuzach',
	Katowice: 'Katowicach',
	'Kazimierza Wielka': 'Kazimierzy Wielkiej',
	'Kędzierzyn-Koźle': 'Kędzierzynie-Koźlu',
	Kępno: 'Kępnie',
	Kętrzyn: 'Kętrzynie',
	Kęty: 'Kętach',
	Kielce: 'Kielcach',
	Kłobuck: 'Kłobucku',
	Kłodzko: 'Kłodzku',
	Kluczbork: 'Kluczborku',
	Knurów: 'Knurowie',
	Kobyłka: 'Kobyłce',
	Kolbuszowa: 'Kolbuszowej',
	Kolno: 'Kolnie',
	Koło: 'Kole',
	Kołobrzeg: 'Kołobrzegu',
	Koluszki: 'Koluszkach',
	Komorniki: 'Komornikach',
	Konin: 'Koninie',
	Końskie: 'Końskich',
	'Konstancin-Jeziorna': 'Konstancinie-Jeziornie',
	'Konstantynów Łódzki': 'Konstantynowie Łódzkim',
	Koronowo: 'Koronowie',
	Kościan: 'Kościanie',
	Kościerzyna: 'Kościerzynie',
	'Kostrzyn nad Odrą': 'Kostrzynie nad Odrą',
	Koszalin: 'Koszalinie',
	Kowale: 'Kowalach',
	'Kowalewo Pomorskie': 'Kowalewie Pomorskim',
	Koziegłowy: 'Koziegłowach',
	Kozienice: 'Kozienicach',
	Kraków: 'Krakowie',
	Krapkowice: 'Krapkowicach',
	Kraśnik: 'Kraśniku',
	Krasnystaw: 'Krasnymstawie',
	Krosno: 'Krośnie',
	'Krosno Odrzańskie': 'Krośnie Odrzańskim',
	Krotoszyn: 'Krotoszynie',
	Kruszwica: 'Kruszwicy',
	'Krynica-Zdrój': 'Krynicy-Zdroju',
	Krzeszowice: 'Krzeszowicach',
	'Kudowa-Zdrój': 'Kudowie-Zdroju',
	Kutno: 'Kutnie',
	Kwidzyn: 'Kwidzynie',
	Łagów: 'Łagowie',
	Łańcut: 'Łańcucie',
	Łapy: 'Łapach',
	Łask: 'Łasku',
	'Łaziska Górne': 'Łaziskach Górnych',
	Łazy: 'Łazach',
	Łeba: 'Łebie',
	Lębork: 'Lęborku',
	Łęczna: 'Łęcznej',
	Łęczyca: 'Łęczycy',
	Legionowo: 'Legionowie',
	Legnica: 'Legnicy',
	Leszno: 'Lesznie',
	Leżajsk: 'Leżajsku',
	Libiąż: 'Libiążu',
	'Lidzbark Warmiński': 'Lidzbarku Warmińskim',
	Limanowa: 'Limanowej',
	Lipienice: 'Lipienicach',
	Lipno: 'Lipnie',
	Lipsko: 'Lipsku',
	Łobez: 'Łobzie',
	Łódź: 'Łodzi',
	Łomianki: 'Łomiankach',
	Łomża: 'Łomży',
	Łosice: 'Łosicach',
	Łowicz: 'Łowiczu',
	Lubaczów: 'Lubaczowie',
	Lubań: 'Lubaniu',
	Lubartów: 'Lubartowie',
	Lubawa: 'Lubawie',
	Lubin: 'Lubinie',
	Lublin: 'Lublinie',
	Lubliniec: 'Lublińcu',
	Luboń: 'Luboniu',
	Lubsko: 'Lubsku',
	Łuków: 'Łukowie',
	'Lwówek Śląski': 'Lwówku Śląskim',
	'Maków Mazowiecki': 'Makowie Mazowieckim',
	Malbork: 'Malborku',
	Marki: 'Markach',
	Miastko: 'Miastku',
	Miechów: 'Miechowie',
	Międzychód: 'Międzychodzie',
	'Międzyrzec Podlaski': 'Międzyrzecu Podlaskim',
	Międzyrzecz: 'Międzyrzeczu',
	Międzyzdroje: 'Międzyzdrojach',
	Mielec: 'Mielcu',
	Mikołów: 'Mikołowie',
	Milanówek: 'Milanówku',
	Milicz: 'Miliczu',
	'Mińsk Mazowiecki': 'Mińsku Mazowieckim',
	Mława: 'Mławie',
	Mogilno: 'Mogilnie',
	Mońki: 'Mońkach',
	Mosina: 'Mosinie',
	Mrągowo: 'Mrągowie',
	Myślenice: 'Myślenicach',
	Myślibórz: 'Myśliborzu',
	Mysłowice: 'Mysłowicach',
	Myszków: 'Myszkowie',
	'Nakło nad Notecią': 'Nakle nad Notecią',
	Namysłów: 'Namysłowie',
	Nasielsk: 'Nasielsku',
	Nidzica: 'Nidzicy',
	Niemodlin: 'Niemodlinie',
	Niepołomice: 'Niepołomicach',
	Nisko: 'Nisku',
	'Nowa Ruda': 'Nowej Rudzie',
	'Nowa Sól': 'Nowej Soli',
	'Nowa Wieś': 'Nowej Wsi',
	'Nowe Miasto Lubawskie': 'Nowym Mieście Lubawskim',
	Nowogard: 'Nowogardzie',
	'Nowy Dwór Gdański': 'Nowym Dworze Gdańskim',
	'Nowy Dwór Mazowiecki': 'Nowym Dworze Mazowieckim',
	'Nowy Sącz': 'Nowym Sączu',
	'Nowy Targ': 'Nowym Targu',
	'Nowy Tomyśl': 'Nowym Tomyślu',
	Nysa: 'Nysie',
	Oborniki: 'Obornikach',
	Oława: 'Oławie',
	Olecko: 'Olecku',
	Oleśnica: 'Oleśnicy',
	Olesno: 'Oleśnie',
	Olkusz: 'Olkuszu',
	Olsztyn: 'Olsztynie',
	Opalenica: 'Opalenicy',
	Opatów: 'Opatowie',
	Opoczno: 'Opocznie',
	Opole: 'Opolu',
	'Opole Lubelskie': 'Opolu Lubelskim',
	Orzesze: 'Orzeszu',
	Osiek: 'Osieku',
	Ostróda: 'Ostródzie',
	Ostrołęka: 'Ostrołęce',
	'Ostrów Mazowiecka': 'Ostrowi Mazowieckiej',
	'Ostrów Wielkopolski': 'Ostrowie Wielkopolskim',
	'Ostrowiec Świętokrzyski': 'Ostrowcu Świętokrzyskim',
	Ostrzeszów: 'Ostrzeszowie',
	Oświęcim: 'Oświęcimiu',
	Otwock: 'Otwocku',
	'Ożarów Mazowiecki': 'Ożarowie Mazowieckim',
	Ozorków: 'Ozorkowie',
	Pabianice: 'Pabianicach',
	Pajęczno: 'Pajęcznie',
	Parczew: 'Parczewie',
	Pasłęk: 'Pasłęku',
	Piaseczno: 'Piasecznie',
	Piastów: 'Piastowie',
	'Piekary Śląskie': 'Piekarach Śląskich',
	Piła: 'Pile',
	Pionki: 'Pionkach',
	'Piotrków Trybunalski': 'Piotrkowie Trybunalskim',
	Pisz: 'Piszu',
	Pleszew: 'Pleszewie',
	Plewiska: 'Plewiskach',
	Płock: 'Płocku',
	Płońsk: 'Płońsku',
	Pniewy: 'Pniewach',
	Pobiedziska: 'Pobiedziskach',
	Poddębice: 'Poddębicach',
	'Podkowa Leśna': 'Podkowie Leśnej',
	Pogórze: 'Pogórzu',
	Połaniec: 'Połańcu',
	Police: 'Policach',
	Polkowice: 'Polkowicach',
	Poznań: 'Poznaniu',
	Praszka: 'Praszce',
	Prudnik: 'Prudniku',
	'Pruszcz Gdański': 'Pruszczu Gdańskim',
	Pruszków: 'Pruszkowie',
	Przasnysz: 'Przasnyszu',
	Przemyśl: 'Przemyślu',
	Przeworsk: 'Przeworsku',
	Pszczyna: 'Pszczynie',
	Puck: 'Pucku',
	Puławy: 'Puławach',
	Pułtusk: 'Pułtusku',
	Pyrzyce: 'Pyrzycach',
	Pyskowice: 'Pyskowicach',
	'Rabka-Zdrój': 'Rabce-Zdroju',
	Racibórz: 'Raciborzu',
	Radlin: 'Radlinie',
	Radom: 'Radomiu',
	Radomsko: 'Radomsku',
	Radziejów: 'Radziejowie',
	Radzionków: 'Radzionkowie',
	Radzymin: 'Radzyminie',
	'Radzyń Podlaski': 'Radzyniu Podlaskim',
	'Rawa Mazowiecka': 'Rawie Mazowieckiej',
	Rawicz: 'Rawiczu',
	Reda: 'Redzie',
	Rogoźno: 'Rogoźnie',
	Rokietnica: 'Rokietnicy',
	Ropczyce: 'Ropczycach',
	'Ruda Śląska': 'Rudzie Śląskiej',
	Rumia: 'Rumi',
	Ruszowice: 'Ruszowicach',
	Rybnik: 'Rybniku',
	Rydułtowy: 'Rydułtowach',
	Ryki: 'Rykach',
	Rypin: 'Rypinie',
	Rzepin: 'Rzepinie',
	Rzeszów: 'Rzeszowie',
	Rzgów: 'Rzgowie',
	Sandomierz: 'Sandomierzu',
	Sanok: 'Sanoku',
	'Sędziszów Małopolski': 'Sędziszowie Małopolskim',
	'Sępólno Krajeńskie': 'Sępólnie Krajeńskim',
	Serock: 'Serocku',
	Siedlce: 'Siedlcach',
	'Siemianowice Śląskie': 'Siemianowicach Śląskich',
	Siemiatycze: 'Siemiatyczach',
	Sieradz: 'Sieradzu',
	Sierakowice: 'Sierakowicach',
	Sierpc: 'Sierpcu',
	Siewierz: 'Siewierzu',
	'Skarżysko-Kamienna': 'Skarżysku-Kamiennej',
	Skawina: 'Skawinie',
	Skierniewice: 'Skierniewicach',
	Skórzewo: 'Skórzewie',
	Skwierzyna: 'Skwierzynie',
	Sławno: 'Sławnie',
	Słubice: 'Słubicach',
	Słupca: 'Słupcy',
	Słupsk: 'Słupsku',
	Smolec: 'Smolcu',
	Sochaczew: 'Sochaczewie',
	Sokółka: 'Sokółce',
	'Sokołów Podlaski': 'Sokołowie Podlaskim',
	Sopot: 'Sopocie',
	Sosnowiec: 'Sosnowcu',
	Śrem: 'Śremie',
	'Środa Śląska': 'Środzie Śląskiej',
	'Środa Wielkopolska': 'Środzie Wielkopolskiej',
	'Stalowa Wola': 'Stalowej Woli',
	Starachowice: 'Starachowicach',
	Stargard: 'Stargardzie',
	'Starogard Gdański': 'Starogardzie Gdańskim',
	Staszów: 'Staszowie',
	Strzegom: 'Strzegomiu',
	'Strzelce Krajeńskie': 'Strzelcach Krajeńskich',
	'Strzelce Opolskie': 'Strzelcach Opolskich',
	Strzelin: 'Strzelinie',
	Strzyżów: 'Strzyżowie',
	'Sucha Beskidzka': 'Suchej Beskidzkiej',
	'Suchy Las': 'Suchym Lesie',
	Sulechów: 'Sulechowie',
	Sulęcin: 'Sulęcinie',
	Sulejówek: 'Sulejówku',
	Suwałki: 'Suwałkach',
	Swarzędz: 'Swarzędzu',
	Świdnica: 'Świdnicy',
	Świdnik: 'Świdniku',
	Świdwin: 'Świdwinie',
	Świebodzice: 'Świebodzicach',
	Świebodzin: 'Świebodzinie',
	Świecie: 'Świeciu',
	Świętochłowice: 'Świętochłowicach',
	Świnoujście: 'Świnoujściu',
	Syców: 'Sycowie',
	Szamotuły: 'Szamotułach',
	Szczecin: 'Szczecinie',
	Szczecinek: 'Szczecinku',
	Szczytno: 'Szczytnie',
	Szprotawa: 'Szprotawie',
	Szubin: 'Szubinie',
	Szydłowiec: 'Szydłowcu',
	Tarczyn: 'Tarczynie',
	Tarnobrzeg: 'Tarnobrzegu',
	Tarnów: 'Tarnowie',
	'Tarnowo Podgórne': 'Tarnowie Podgórnym',
	'Tarnowskie Góry': 'Tarnowskich Górach',
	Tczew: 'Tczewie',
	'Tomaszów Lubelski': 'Tomaszowie Lubelskim',
	'Tomaszów Mazowiecki': 'Tomaszowie Mazowieckim',
	Toruń: 'Toruniu',
	Trzcianka: 'Trzciance',
	Trzebiatów: 'Trzebiatowie',
	Trzebinia: 'Trzebini',
	Trzebnica: 'Trzebnicy',
	Tuchola: 'Tucholi',
	Turek: 'Turku',
	Tychy: 'Tychach',
	Ustka: 'Ustce',
	Ustroń: 'Ustroniu',
	'Ustrzyki Dolne': 'Ustrzykach Dolnych',
	Wąbrzeźno: 'Wąbrzeźnie',
	Wadowice: 'Wadowicach',
	Wągrowiec: 'Wągrowcu',
	Wałbrzych: 'Wałbrzychu',
	Wałcz: 'Wałczu',
	Warka: 'Warce',
	Warszawa: 'Warszawie',
	Węgorzewo: 'Węgorzewie',
	Węgrów: 'Węgrowie',
	Wejherowo: 'Wejherowie',
	Wieliczka: 'Wieliczce',
	Wieluń: 'Wieluniu',
	Wieruszów: 'Wieruszowie',
	Wisła: 'Wiśle',
	Witnica: 'Witnicy',
	Władysławowo: 'Władysławowie',
	Włocławek: 'Włocławku',
	Włodawa: 'Włodawie',
	Włoszczowa: 'Włoszczowie',
	'Wodzisław Śląski': 'Wodzisławiu Śląskim',
	Wojkowice: 'Wojkowicach',
	Wołomin: 'Wołominie',
	Wołów: 'Wołowie',
	Wolsztyn: 'Wolsztynie',
	Wrocław: 'Wrocławiu',
	Wronki: 'Wronkach',
	Września: 'Wrześni',
	Wschowa: 'Wschowie',
	Wyszków: 'Wyszkowie',
	Ząbki: 'Ząbkach',
	'Ząbkowice Śląskie': 'Ząbkowicach Śląskich',
	Zabrze: 'Zabrzu',
	Żagań: 'Żaganiu',
	Zakopane: 'Zakopanem',
	Zalasewo: 'Zalasewie',
	Zambrów: 'Zambrowie',
	Zamość: 'Zamościu',
	Żary: 'Żarach',
	Zawada: 'Zawadzie',
	Zawiercie: 'Zawierciu',
	'Zduńska Wola': 'Zduńskiej Woli',
	Zdzieszowice: 'Zdzieszowicach',
	Zgierz: 'Zgierzu',
	Zgorzelec: 'Zgorzelcu',
	'Zielona Góra': 'Zielonej Górze',
	Zielonka: 'Zielonce',
	Złocieniec: 'Złocieńcu',
	Złotoryja: 'Złotoryi',
	Żnin: 'Żninie',
	Żory: 'Żorach',
	Żukowo: 'Żukowie',
	Żuromin: 'Żurominie',
	Zwoleń: 'Zwoleniu',
	Żyrardów: 'Żyrardowie',
	Żywiec: 'Żywcu',
};

/** "w"/"we" before a locative: "we" when the form starts with w/f + consonant
 *  ("we Wrocławiu", "we Wschowie") or with "Lw" ("we Lwówku Śląskim"). */
function preposition(loc: string): 'w' | 'we' {
	return /^(?:[wf][^aeiouyąęó]|lw)/i.test(loc) ? 'we' : 'w';
}

/** "we Wrocławiu", "w Krakowie" — or "w miejscowości Nowe Miasto" when the
 *  city is not in the curated table. */
export function cityInPhrase(city: string): string {
	const loc = CITY_LOCATIVE[city.trim()];
	return loc ? `${preposition(loc)} ${loc}` : `w miejscowości ${city}`;
}
